development:
  twitter:
    key: vKz011Lx017SORfImYyQeqtkk
    secret: KLhAcbKubzDyKp5nJSWaK17j3vWCm8IQbQrheFOdx4GcG3SgWF
test:
  twitter:
    key: vKz011Lx017SORfImYyQeqtkk
    secret: KLhAcbKubzDyKp5nJSWaK17j3vWCm8IQbQrheFOdx4GcG3SgWF
production:
  twitter:
    key: <%= ENV["TWITTER_KEY"] %>
    secret: <%= ENV["TWITTER_SECRET"] %>
